# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Install playwright browsers
RUN npx playwright install

# Copy the rest of the application code
COPY . .

# Build the application (transpile TypeScript)
RUN npm run build

# Expose port if needed (currently not used, MCP runs via stdio)

# Default command to start the MCP server
CMD [ "node", "cli.js" ]
